package com.wex.transaction.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * Data Transfer Object for the response when a purchase transaction is created
 * 
 * This DTO returns the details of the newly created transaction, including
 * the auto-generated unique identifier assigned by the system.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class CreatePurchaseTransactionResponse {

    /**
     * Unique identifier assigned to the transaction
     * Generated by the system to uniquely identify this purchase
     */
    private String id;

    /**
     * Echo of the submitted description
     */
    private String description;

    /**
     * Echo of the submitted transaction date
     */
    private LocalDate transactionDate;

    /**
     * Echo of the submitted amount in US dollars
     */
    private BigDecimal amountUsd;

    /**
     * Human-readable success message
     */
    private String message;
}
